import java.io.*; 
 
public class Pra31 { 
    public static void main(String[] args) { 
        try { 
            BufferedReader consoleReader = new BufferedReader(new 
InputStreamReader(System.in)); 
 
            System.out.println("Enter some text to write to the file (Pr31.java):"); 
            String userInput = consoleReader.readLine(); 
 
            BufferedWriter fileWriter = new BufferedWriter(new FileWriter("Pr31.java")); 
            fileWriter.write("// This file is generated by the program\n"); 
            fileWriter.write("/* User input: " + userInput + " */\n"); 
            fileWriter.write("public class Pra31 {\n"); 
            fileWriter.write("    public static void main(String[] args) {\n"); 
            fileWriter.write("        System.out.println(\"" + userInput + "\");\n"); 
            fileWriter.write("    }\n"); 
            fileWriter.write("}\n"); 
 
            fileWriter.close();  
 
            System.out.println("Data written to file successfully (Pra31.java)"); 
 
             
            FileInputStream fileInputStream = new FileInputStream("Pra31.java"); 
            System.out.println("\nReading from file (using byte stream):");
            int byteData; 
            while ((byteData = fileInputStream.read()) != -1) { 
                System.out.print((char) byteData);  
            } 
 
            fileInputStream.close();  
 
        } catch (IOException e) { 
            e.printStackTrace(); 
        } 
    } 
} 
